global:
  image: {}
  rollingUpdate: {}
  minions:
    image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.minions.image.x
# - Values.global.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-minion-knowledge-graph"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  tag: 1.0.0
  pullPolicy: IfNotPresent
  imagePullSecret: false

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

resources:
  requests:
    cpu: 500m
    memory: 5000Mi
  limits:
    cpu: 1000m

neo4j:
  # -- neo4j DB access url in cluster 
  url: bolt://graph-db:7687
  # -- neo4j DB access username
  username: neo4j
  # -- neo4j DB access password.
  # leave blank will auto-load from the secret.
  password: 

